### PR TITLE
data: control_number addition

### PR DESCRIPTION
**Pull request by hachreak**
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

### CODE REVIEW

**Comment by switowski** [comment]
Hey, could you, please, add a short comment in the commit message on why the control numbers are needed for ?

**Comment by jirikuncar** [comment]
Do we really need to force the control number?

**Comment by hachreak** [comment]
For loading the [bibliographic.xml](https://github.com/hachreak/invenio/blob/index_page/scripts/populate-instance.sh#L125-L150) into the db 
we had to choose:
 - set the `control_number` here and then set the `pid_value=record['control_number']`
 - call `recid_minter` to create the `pid_value` and then update the `record['control_number'] = pid_value`

We have choosen the first solution. @lnielsen @switowski @egabancho 
p.s. I started also to create a branch to implement the [minting](https://github.com/hachreak/invenio-pidstore/tree/recid_minter_cli). 
I'll leave there, just in case we change idea..

**Comment by jirikuncar** [comment]
`recid_minter` already updates `record['control_number']`

**Comment by hachreak** [comment]
Already exists a CLI command to call `recid_minter`?

**Pull request merged**
