### PR TITLE
signals: before_record_index

### LINKED ISSUE #48: signals: record enhancers
In order to enhance on the fly a record being sent to elasticsearch for indexing a receiver for the events `after_record_insert`, `after_record_update` needs to be created that would execute all the enhancers collected via a registry, passing the current record being sent and returning an enhanced record.

### PR DESCRIPTION
**Pull request by kaplun**
* NEW Introduces new signal before_record_index, which is triggered
  in index_record() task, in order to enhance on the fly the JSON
  being set to Elasticsearch.
  (closes #48)

Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
Note: this does simply introduce a new signal, which should be enough in order to enhance on the fly records being sent to Elasticsearch. The introduction of a registry part is optional and can later be introduced as one of the listening receivers.

**Comment by kaplun** [comment]
cc: @egabancho, @jirikuncar

**Comment by kaplun** [comment]
@jirikuncar code amended as per review.

**Comment by lnielsen** [comment]
Closing this PR per discussion in #48 and inveniosoftware/invenio-search#32

**Pull request closed without merging**
