### PR TITLE
global: removal of access permissions

### LINKED ISSUE #137: RFC Removal of default permissions
### Proposal

Can we remove `invenio_records.permissions` module as it is not recommended for large repositories to store per record access rights in `invenio-access`?

--
cc @inveniosoftware/triagers

### PR DESCRIPTION
**Pull request by jirikuncar**
closes #137

### CODE REVIEW

**Comment by hachreak** [comment]
I think you should before make a PR to clean 
 - [invenio-records-rest](https://github.com/inveniosoftware/invenio-records-rest/blob/master/tests/access_records.py#L38)
 - invenio-records-ui [example](https://github.com/inveniosoftware/invenio-records-ui/blob/master/examples/permsapp.py#L68) and [tests](https://github.com/inveniosoftware/invenio-records-ui/blob/master/tests/test_invenio_records_ui.py#L43).

**Comment by hachreak** [comment]
Is [tests/access_records.py](https://github.com/inveniosoftware/invenio-records-rest/blob/master/tests/access_records.py) used anywhere?
because I can't find any import at least in `invenio-records-rest`.

**Comment by jirikuncar** [comment]
IMHO we can remove it (cc @nharraud).

**Comment by nharraud** [comment]
Looks good :shipit:
Thanks @hachreak

**Comment by hachreak** [comment]
@jirikuncar should I create there a default permission factory? see https://github.com/inveniosoftware/invenio-records-ui/blob/master/invenio_records_ui/config.py#L33

**Pull request merged**
