### PR TITLE
api: signals connected to an app

### LINKED ISSUE #165: api: signals should be connected to an app
Make sure that all signals are emitted using `current_app._get_current_object()`.

```python
signal_foo.send(current_app._get_current_object(), record=record)
```

--
http://flask.pocoo.org/docs/0.12/signals/#sending-signals

### PR DESCRIPTION
**Pull request by jbenito3**
* Sends signals always connected to the current app. (closes #165)

Signed-off-by: Jose Benito Gonzalez Lopez <jose.benito.gonzalez@cern.ch>

### CODE REVIEW

**Comment by drjova** [comment]
@jbenito3  👍 LGTM could you please update the copyright year?

**Comment by jbenito3** [comment]
@drjova thanks! done :)

**Comment by lnielsen** [comment]
This is going to break existing code, so we need to be careful before releasing this.

**Comment by drjova** [comment]
@jbenito3 we have to double check ``invenio-deposit`` which uses these signals

https://github.com/inveniosoftware/invenio-deposit/blob/master/invenio_deposit/api.py#L406

**Comment by drjova** [comment]
https://github.com/inveniosoftware/invenio-deposit/pull/174

**Comment by drjova** [comment]
https://github.com/inveniosoftware/invenio-oaiserver/search?utf8=✓&q=OAIServerUpdater&type=

**Comment by drjova** [comment]
Updated https://github.com/inveniosoftware/invenio-oaiserver/pull/126

**Pull request merged**
