### PR TITLE
cli: record creation without celery

### PR DESCRIPTION
**Pull request by jirikuncar**
* Removes usage of Celery for creating records using CLI.

* Accepts record UUIDs.

Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

### CODE REVIEW

**Comment by tiborsimko** [comment]
Works for me, with some comments:

- The `--record` CLI argument should be probably named `uuid` or `id`, because it denotes "record identifier" entities, not "record body" entities.  (This will also improve the readability of `for record, id_ in zip_longest(data, record)` statements...)

- Using the `--force` CLI argument leads to:

```
File "/home/simko/private/src/invenio-records/invenio_records/cli.py", line 77, in create
  click.echo(Record(data, model=record.model).commit().id)
File "/home/simko/private/src/invenio-records/invenio_records/api.py", line 81, in __init__
  super(RecordBase, self).__init__(data or {})
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

- Without `--force`, an attempt to create a new record with an already-existing UUID could perhaps explicitly exit with the error status code 1 in order to explicitly indicate the failure situation back to the clients.  (Well, they could read UUID and check its "emptiness", but for CLI scripting an explicit exit code may be preferred.)

**Comment by jirikuncar** [comment]
@tiborsimko I have added more tests that should cover your cases (https://travis-ci.org/jirikuncar/invenio-records/builds/95581817)

**Comment by tiborsimko** [comment]
`-i` is generally behaving well:

```
$ echo '{"foo": "Foo"}' | flask -a app.py records create
b9dae8db-e17a-491e-abff-30b6804c5113
$ echo '{"foo2": "Foo2"}' | flask -a app.py records create -i b9dae8db-e17a-491e-abff-30b6804c5119
b9dae8db-e17a-491e-abff-30b6804c5119
```

but I still see some troubles:

```
$ echo '{"foo1": "Foo1"}' | flask -a app.py records create -i b9dae8db-e17a-491e-abff-30b6804c5113
app
Traceback (most recent call last):
  File "/home/simko/.virtualenvs/invenio-records/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/simko/.virtualenvs/invenio-records/local/lib/python2.7/site-packages/flask_cli/cli.py", line 495, in main
    cli.main(args=args, prog_name=name)
  File "/home/simko/.virtualenvs/invenio-records/local/lib/python2.7/site-packages/flask_cli/cli.py", line 343, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/simko/.virtualenvs/invenio-records/local/lib/python2.7/site-packages/click/core.py", line 706, in main
    e.show()
  File "/home/simko/.virtualenvs/invenio-records/local/lib/python2.7/site-packages/click/exceptions.py", line 46, in show
    color = self.ctx.color
AttributeError: 'dict' object has no attribute 'color'
```

and with `--force` it looks like the new input is "accepted" for creation:

```
$ echo '{"foo1": "Foo1"}' | flask -a app.py records create -i b9dae8db-e17a-491e-abff-30b6804c5113 --force
b9dae8db-e17a-491e-abff-30b6804c5113
```

but the record has not changed:

```
>>> pprint.pprint([(r.id, r.json) for r in RecordMetadata.query.all()])
[(UUID('b9dae8db-e17a-491e-abff-30b6804c5113'), {u'foo': u'Foo'})]
```

Perhaps we could handle this use case more explicitly...

**Comment by tiborsimko** [comment]
All OK now on PostgreSQL and SQLlite, merging...

**Pull request merged**
